<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ne laissez pas de traces</title>
    <script src="https://unpkg.com/htmx.org@2.0.3"></script>
</head>
<body >

<section class="top-home-page">
    <div class="left-part">
        <h1>Ne laissez <br /> &nbsp&nbsp;&nbsppas de traces</h1>
        <p class="subtitle">Le site de prévention à l'éthique en nature pour s'éduquer et tester ses connaissances.</p>
        <div class="flex-top-link">
            <!-- TODO Btn en savoir plus sur le sujet -->
        </div>
    </div>
    <img class="img-home" src="/images/illu-home.svg" alt="Illustration d'une femme avec une tente en nature" />
</section>

<section class="prevention" id="jeu">
    <div class="flex-prevention">
        <div class="box-prevention">
            <div class="text-prevention">
                <h2>Je <mark class="green-bg">teste</mark> mes connaissances</h2>
                <p class="instruction-text">
                    Prêt à booster tes connaissances sur les principes Leave no Trace ?
                    Avec notre quiz, tu vas pouvoir vérifier ce que tu sais déjà au sujet de l'éthique en nature et
                    découvrir de nouvelles infos !
                </p>
                <!-- TODO Btn to game -->
            </div>
            <img class="img-home" src="/images/illu-home-2.svg" alt="Illustration d'un homme qui fait un test en ligne" />
        </div>

        <div class="box-prevention">
            <div class="text-prevention">
                <h2>Je suis <span class="yellow-bg">animateur·rice</span></h2>
                <p class="instruction-text">
                    Vous souhaitez organiser un atelier de prévention sur l'éthique en nature ? Bingo, vous êtes au
                    bon endroit ! Retrouvez toutes les étapes détaillées afin de bien préparer votre
                    manifestation dans vos classes.
                </p>
                <!-- TODO Btn to atelier -->
            </div>
            <img class="img-home" src="/images/illu-home-3.svg" alt="Illustration d'un educateur face à sa classe" />
        </div>
    </div>

</section>
<section class="statistique">
    <div class="box-stat">
        <p class="number-stat">56%</p>
        <p class="text-stat">
            des Français, soit 27 millions de personnes
            de plus de 18 ans ont déclaré pratiquer toute forme de randonnée (c’est à dire marche,
            randonnée pédestre, balade) au cours de ces 12 derniers mois<a
                    class="source"
                    href="https://www.ofdt.fr/"
                    target="_blank">(FFRANDONNE, 2023)</a
            >
        </p>
    </div>
  
</section>

<!-- TODO Add ressource section- -->

<!-- TODO Add why section -->
</body>
</html>
